//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LastFMClientWinForm.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ILastFMService")]
    public interface ILastFMService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILastFMService/GetTopTracks", ReplyAction="http://tempuri.org/ILastFMService/GetTopTracksResponse")]
        string[] GetTopTracks(string genre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILastFMService/GetTopTracks", ReplyAction="http://tempuri.org/ILastFMService/GetTopTracksResponse")]
        System.Threading.Tasks.Task<string[]> GetTopTracksAsync(string genre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILastFMService/GetTopTags", ReplyAction="http://tempuri.org/ILastFMService/GetTopTagsResponse")]
        string[] GetTopTags();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILastFMService/GetTopTags", ReplyAction="http://tempuri.org/ILastFMService/GetTopTagsResponse")]
        System.Threading.Tasks.Task<string[]> GetTopTagsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILastFMServiceChannel : LastFMClientWinForm.ServiceReference1.ILastFMService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LastFMServiceClient : System.ServiceModel.ClientBase<LastFMClientWinForm.ServiceReference1.ILastFMService>, LastFMClientWinForm.ServiceReference1.ILastFMService {
        
        public LastFMServiceClient() {
        }
        
        public LastFMServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LastFMServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LastFMServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LastFMServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetTopTracks(string genre) {
            return base.Channel.GetTopTracks(genre);
        }
        
        public System.Threading.Tasks.Task<string[]> GetTopTracksAsync(string genre) {
            return base.Channel.GetTopTracksAsync(genre);
        }
        
        public string[] GetTopTags() {
            return base.Channel.GetTopTags();
        }
        
        public System.Threading.Tasks.Task<string[]> GetTopTagsAsync() {
            return base.Channel.GetTopTagsAsync();
        }
    }
}
